export interface TickerInfo {
  symbol: string;
  name: string;
}

export const POPULAR_TICKERS: TickerInfo[] = [
  // Electronic Technology
  { symbol: 'AAPL', name: 'Apple Inc.' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation' },
  { symbol: 'AMD', name: 'Advanced Micro Devices' },
  { symbol: 'INTC', name: 'Intel Corporation' },
  { symbol: 'QCOM', name: 'Qualcomm Inc.' },
  { symbol: 'AVGO', name: 'Broadcom Inc.' },
  { symbol: 'TXN', name: 'Texas Instruments' },
  { symbol: 'MU', name: 'Micron Technology' },
  { symbol: 'AMAT', name: 'Applied Materials' },
  { symbol: 'KLAC', name: 'KLA Corporation' },
  { symbol: 'LRCX', name: 'Lam Research' },
  { symbol: 'MRVL', name: 'Marvell Technology' },
  { symbol: 'NXPI', name: 'NXP Semiconductors' },
  { symbol: 'ON', name: 'ON Semiconductor' },
  { symbol: 'STX', name: 'Seagate Technology' },
  { symbol: 'WDC', name: 'Western Digital' },
  { symbol: 'HPQ', name: 'HP Inc.' },
  { symbol: 'DELL', name: 'Dell Technologies' },
  // Technology Services
  { symbol: 'MSFT', name: 'Microsoft Corporation' },
  { symbol: 'GOOGL', name: 'Alphabet Inc.' },
  { symbol: 'GOOG', name: 'Alphabet Inc. Class C' },
  { symbol: 'META', name: 'Meta Platforms' },
  { symbol: 'ORCL', name: 'Oracle Corporation' },
  { symbol: 'IBM', name: 'IBM Corporation' },
  { symbol: 'ADBE', name: 'Adobe Inc.' },
  { symbol: 'CRM', name: 'Salesforce Inc.' },
  { symbol: 'NOW', name: 'ServiceNow Inc.' },
  { symbol: 'INTU', name: 'Intuit Inc.' },
  { symbol: 'SNOW', name: 'Snowflake Inc.' },
  { symbol: 'PLTR', name: 'Palantir Technologies' },
  { symbol: 'UBER', name: 'Uber Technologies' },
  { symbol: 'LYFT', name: 'Lyft Inc.' },
  { symbol: 'TWLO', name: 'Twilio Inc.' },
  { symbol: 'NET', name: 'Cloudflare Inc.' },
  { symbol: 'DDOG', name: 'Datadog Inc.' },
  { symbol: 'ZS', name: 'Zscaler Inc.' },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings' },
  { symbol: 'FTNT', name: 'Fortinet Inc.' },
  { symbol: 'PANW', name: 'Palo Alto Networks' },
  { symbol: 'OKTA', name: 'Okta Inc.' },
  { symbol: 'TEAM', name: 'Atlassian Corporation' },
  { symbol: 'WDAY', name: 'Workday Inc.' },
  { symbol: 'VEEV', name: 'Veeva Systems' },
  { symbol: 'ZM', name: 'Zoom Video' },
  { symbol: 'SHOP', name: 'Shopify Inc.' },
  { symbol: 'SPOT', name: 'Spotify Technology' },
  { symbol: 'RBLX', name: 'Roblox Corporation' },
  // Finance
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.' },
  { symbol: 'BAC', name: 'Bank of America' },
  { symbol: 'WFC', name: 'Wells Fargo & Co.' },
  { symbol: 'GS', name: 'Goldman Sachs Group' },
  { symbol: 'MS', name: 'Morgan Stanley' },
  { symbol: 'C', name: 'Citigroup Inc.' },
  { symbol: 'AXP', name: 'American Express' },
  { symbol: 'BLK', name: 'BlackRock Inc.' },
  { symbol: 'SCHW', name: 'Charles Schwab' },
  { symbol: 'USB', name: 'U.S. Bancorp' },
  { symbol: 'PNC', name: 'PNC Financial Services' },
  { symbol: 'TFC', name: 'Truist Financial' },
  { symbol: 'COF', name: 'Capital One Financial' },
  { symbol: 'DFS', name: 'Discover Financial' },
  { symbol: 'SYF', name: 'Synchrony Financial' },
  { symbol: 'V', name: 'Visa Inc.' },
  { symbol: 'MA', name: 'Mastercard Inc.' },
  { symbol: 'PYPL', name: 'PayPal Holdings' },
  { symbol: 'SQ', name: 'Block Inc.' },
  { symbol: 'AFRM', name: 'Affirm Holdings' },
  { symbol: 'COIN', name: 'Coinbase Global' },
  { symbol: 'ICE', name: 'Intercontinental Exchange' },
  { symbol: 'CME', name: 'CME Group Inc.' },
  { symbol: 'SPGI', name: "S&P Global Inc." },
  { symbol: 'MCO', name: "Moody's Corporation" },
  // Health Technology
  { symbol: 'LLY', name: 'Eli Lilly and Company' },
  { symbol: 'JNJ', name: 'Johnson & Johnson' },
  { symbol: 'UNH', name: 'UnitedHealth Group' },
  { symbol: 'PFE', name: 'Pfizer Inc.' },
  { symbol: 'ABBV', name: 'AbbVie Inc.' },
  { symbol: 'MRK', name: 'Merck & Co.' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific' },
  { symbol: 'ABT', name: 'Abbott Laboratories' },
  { symbol: 'DHR', name: 'Danaher Corporation' },
  { symbol: 'AMGN', name: 'Amgen Inc.' },
  { symbol: 'GILD', name: 'Gilead Sciences' },
  { symbol: 'BIIB', name: 'Biogen Inc.' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals' },
  { symbol: 'MRNA', name: 'Moderna Inc.' },
  { symbol: 'ISRG', name: 'Intuitive Surgical' },
  { symbol: 'BSX', name: 'Boston Scientific' },
  { symbol: 'MDT', name: 'Medtronic plc' },
  { symbol: 'EW', name: 'Edwards Lifesciences' },
  { symbol: 'CVS', name: 'CVS Health' },
  { symbol: 'CI', name: 'Cigna Group' },
  { symbol: 'HUM', name: 'Humana Inc.' },
  // Retail Trade
  { symbol: 'AMZN', name: 'Amazon.com Inc.' },
  { symbol: 'WMT', name: 'Walmart Inc.' },
  { symbol: 'COST', name: 'Costco Wholesale' },
  { symbol: 'TGT', name: 'Target Corporation' },
  { symbol: 'HD', name: 'Home Depot Inc.' },
  { symbol: 'LOW', name: "Lowe's Companies" },
  { symbol: 'NKE', name: 'Nike Inc.' },
  { symbol: 'TJX', name: 'TJX Companies' },
  { symbol: 'MCD', name: "McDonald's Corporation" },
  { symbol: 'SBUX', name: 'Starbucks Corporation' },
  { symbol: 'CMG', name: 'Chipotle Mexican Grill' },
  { symbol: 'YUM', name: 'Yum! Brands' },
  { symbol: 'DG', name: 'Dollar General' },
  { symbol: 'DLTR', name: 'Dollar Tree' },
  { symbol: 'ROST', name: 'Ross Stores' },
  { symbol: 'EBAY', name: 'eBay Inc.' },
  { symbol: 'ETSY', name: 'Etsy Inc.' },
  { symbol: 'W', name: 'Wayfair Inc.' },
  // Consumer Durables
  { symbol: 'TSLA', name: 'Tesla Inc.' },
  { symbol: 'GM', name: 'General Motors' },
  { symbol: 'F', name: 'Ford Motor Company' },
  { symbol: 'RIVN', name: 'Rivian Automotive' },
  { symbol: 'LCID', name: 'Lucid Group' },
  { symbol: 'NVR', name: 'NVR Inc.' },
  { symbol: 'PHM', name: 'PulteGroup Inc.' },
  { symbol: 'LEN', name: 'Lennar Corporation' },
  { symbol: 'DHI', name: 'D.R. Horton' },
  { symbol: 'TOL', name: 'Toll Brothers' },
  { symbol: 'WHR', name: 'Whirlpool Corporation' },
  { symbol: 'APTV', name: 'Aptiv PLC' },
  // Energy
  { symbol: 'XOM', name: 'Exxon Mobil' },
  { symbol: 'CVX', name: 'Chevron Corporation' },
  { symbol: 'COP', name: 'ConocoPhillips' },
  { symbol: 'EOG', name: 'EOG Resources' },
  { symbol: 'SLB', name: 'SLB (Schlumberger)' },
  { symbol: 'PSX', name: 'Phillips 66' },
  { symbol: 'MPC', name: 'Marathon Petroleum' },
  { symbol: 'VLO', name: 'Valero Energy' },
  { symbol: 'OXY', name: 'Occidental Petroleum' },
  { symbol: 'HAL', name: 'Halliburton Company' },
  { symbol: 'DVN', name: 'Devon Energy' },
  { symbol: 'PXD', name: 'Pioneer Natural Resources' },
  // ETFs
  { symbol: 'SPY', name: 'SPDR S&P 500 ETF' },
  { symbol: 'QQQ', name: 'Invesco QQQ Trust' },
  { symbol: 'IWM', name: 'iShares Russell 2000 ETF' },
  { symbol: 'DIA', name: 'SPDR Dow Jones ETF' },
  { symbol: 'VTI', name: 'Vanguard Total Market ETF' },
  { symbol: 'VOO', name: 'Vanguard S&P 500 ETF' },
  { symbol: 'ARKK', name: 'ARK Innovation ETF' },
  { symbol: 'GLD', name: 'SPDR Gold Trust' },
  { symbol: 'SLV', name: 'iShares Silver Trust' },
  { symbol: 'TLT', name: 'iShares 20+ Year Treasury' },
  { symbol: 'HYG', name: 'iShares High Yield Corp Bond' },
  // Other large caps
  { symbol: 'BRK-B', name: 'Berkshire Hathaway B' },
  { symbol: 'NFLX', name: 'Netflix Inc.' },
  { symbol: 'DIS', name: 'Walt Disney Company' },
  { symbol: 'CMCSA', name: 'Comcast Corporation' },
  { symbol: 'T', name: 'AT&T Inc.' },
  { symbol: 'VZ', name: 'Verizon Communications' },
  { symbol: 'TMUS', name: 'T-Mobile US' },
  { symbol: 'BA', name: 'Boeing Company' },
  { symbol: 'CAT', name: 'Caterpillar Inc.' },
  { symbol: 'DE', name: 'Deere & Company' },
  { symbol: 'HON', name: 'Honeywell International' },
  { symbol: 'MMM', name: '3M Company' },
  { symbol: 'GE', name: 'GE Aerospace' },
  { symbol: 'RTX', name: 'RTX Corporation' },
  { symbol: 'LMT', name: 'Lockheed Martin' },
  { symbol: 'NOC', name: 'Northrop Grumman' },
  { symbol: 'PG', name: 'Procter & Gamble' },
  { symbol: 'KO', name: 'Coca-Cola Company' },
  { symbol: 'PEP', name: 'PepsiCo Inc.' },
  { symbol: 'PM', name: 'Philip Morris International' },
  { symbol: 'MO', name: 'Altria Group' },
  { symbol: 'CL', name: 'Colgate-Palmolive' },
  { symbol: 'GIS', name: 'General Mills' },
  { symbol: 'K', name: "Kellogg's (Kellanova)" },
  { symbol: 'NEE', name: 'NextEra Energy' },
  { symbol: 'DUK', name: 'Duke Energy' },
  { symbol: 'SO', name: 'Southern Company' },
  { symbol: 'AMT', name: 'American Tower' },
  { symbol: 'PLD', name: 'Prologis Inc.' },
  { symbol: 'EQIX', name: 'Equinix Inc.' },
];

export function searchTickers(query: string, limit = 8): TickerInfo[] {
  if (!query.trim()) return [];
  const q = query.toUpperCase();
  const symbolMatches = POPULAR_TICKERS.filter((t) => t.symbol.startsWith(q));
  const nameMatches = POPULAR_TICKERS.filter(
    (t) => !t.symbol.startsWith(q) && t.name.toUpperCase().includes(q)
  );
  return [...symbolMatches, ...nameMatches].slice(0, limit);
}
